[package]
name = "window_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ctrlc = "3.2.5"
gfx = "0.18.2"
gl = "0.14.0"
glfw = "0.51.0"
libc = "0.2.139"

